#!/usr/bin/env bash

composeCommand=$(dirname $(dirname "$0"))/shortcuts/compose
compose="$composeCommand -f docker-compose.yml -f support/docker-compose.test.yml"

# Run phpspec tests
$compose run --no-deps php bin/phpspec run && \

# Run integration/E2E tests
$compose up -d database && \
$compose run --no-deps php bin/healthcheck 10 && \
$compose run --no-deps php bin/behat

if [ $? -eq 0 ]
then
  echo "Tests passed!"
else
  echo "Tests failed!" >&2
fi

# Cleanup after tests
$compose kill && \
$compose rm -f -v
