#!/usr/bin/env bash

# setup project name
set -a
[ -f .env ] && . .env
set +a

COMPOSE_PROJECT_NAME="{$COMPOSE_PROJECT_NAME}_test"

compose="docker-compose -f docker-compose.yml -f support/docker-compose.test.yml"

# Run phpspec tests
$compose run --no-deps php bin/phpspec run && \

# Run integration/E2E tests
$compose up --no-deps -d database && \
$compose run --rm --no-deps php bin/healthcheck 10 && \
$compose run --rm --no-deps php bin/behat

if [ $? -eq 0 ]
then
  echo "Tests passed!"
else
  echo "Tests failed!" >&2
fi

# Cleanup after tests
$compose kill && \
$compose rm -f -v
